"""Constants for Nursery Soother."""

from typing import Final

from homeassistant.const import Platform

CONF_ATTENTION_SECONDS = "attention_seconds"
CONF_AUTOMATIC_OPERATION = "automatic_operation"
CONF_BASELINE_PREVIEW = "baseline_preview"
CONF_BASELINE_SOUND = "baseline_sound"
CONF_BASELINE_VOLUME = "baseline_volume"
CONF_CAMERA = "camera"
CONF_CRY_GAP_SECONDS = "cry_gap_seconds"
CONF_CRY_SENSOR = "cry_sensor"
CONF_DEBOUNCE_SECONDS = "debounce_seconds"
CONF_DECREASE_LEVEL_TRIGGERS = "decrease_level_triggers"
CONF_EVIDENCE_WINDOW_SECONDS = "evidence_window_seconds"
CONF_INCREASE_LEVEL_TRIGGERS = "increase_level_triggers"
CONF_LEVEL = "level"
CONF_LEVEL_LOCK = "level_lock"
CONF_LEVEL_1_SOUND = "level_1_sound"
CONF_LEVEL_1_VOLUME = "level_1_volume"
CONF_LEVEL_2_SOUND = "level_2_sound"
CONF_LEVEL_2_VOLUME = "level_2_volume"
CONF_LEVEL_3_SOUND = "level_3_sound"
CONF_LEVEL_3_VOLUME = "level_3_volume"
CONF_LEVEL_4_SOUND = "level_4_sound"
CONF_LEVEL_4_VOLUME = "level_4_volume"
CONF_LEVEL_UP_SECONDS = "level_up_seconds"
CONF_MAX_VOLUME = "max_volume"
CONF_MEDIA_PLAYER = "media_player"
CONF_NOTIFY_TARGETS = "notify_targets"
CONF_PROVISIONAL_SECONDS = "provisional_seconds"
CONF_SETTLING_SECONDS = "settling_seconds"
CONF_SOUNDS = "sounds"
CONF_TOGGLE_TRIGGERS = "toggle_triggers"

DEFAULT_ATTENTION_SECONDS = 150
DEFAULT_AUTOMATIC_OPERATION = False
DEFAULT_BASELINE_VOLUME = 10.0
DEFAULT_CRY_GAP_SECONDS = 60
DEFAULT_DEBOUNCE_SECONDS = 8
DEFAULT_EVIDENCE_WINDOW_SECONDS = 30
DEFAULT_LEVEL = "standby"
DEFAULT_LEVEL_LOCK = False
DEFAULT_LEVEL_1_VOLUME = 15.0
DEFAULT_LEVEL_2_VOLUME = 20.0
DEFAULT_LEVEL_3_VOLUME = 25.0
DEFAULT_LEVEL_4_VOLUME = 30.0
DEFAULT_LEVEL_UP_SECONDS = 20
DEFAULT_MAX_VOLUME = 40.0
DEFAULT_PROVISIONAL_SECONDS = 25
DEFAULT_SETTLING_SECONDS = 120

DEFAULT_OPTIONS: Final[dict[str, float | int | bool | str]] = {
    CONF_LEVEL: DEFAULT_LEVEL,
    CONF_LEVEL_LOCK: DEFAULT_LEVEL_LOCK,
    CONF_AUTOMATIC_OPERATION: DEFAULT_AUTOMATIC_OPERATION,
    CONF_BASELINE_VOLUME: DEFAULT_BASELINE_VOLUME,
    CONF_LEVEL_1_VOLUME: DEFAULT_LEVEL_1_VOLUME,
    CONF_LEVEL_2_VOLUME: DEFAULT_LEVEL_2_VOLUME,
    CONF_LEVEL_3_VOLUME: DEFAULT_LEVEL_3_VOLUME,
    CONF_LEVEL_4_VOLUME: DEFAULT_LEVEL_4_VOLUME,
    CONF_MAX_VOLUME: DEFAULT_MAX_VOLUME,
    CONF_DEBOUNCE_SECONDS: DEFAULT_DEBOUNCE_SECONDS,
    CONF_EVIDENCE_WINDOW_SECONDS: DEFAULT_EVIDENCE_WINDOW_SECONDS,
    CONF_CRY_GAP_SECONDS: DEFAULT_CRY_GAP_SECONDS,
    CONF_PROVISIONAL_SECONDS: DEFAULT_PROVISIONAL_SECONDS,
    CONF_LEVEL_UP_SECONDS: DEFAULT_LEVEL_UP_SECONDS,
    CONF_SETTLING_SECONDS: DEFAULT_SETTLING_SECONDS,
    CONF_ATTENTION_SECONDS: DEFAULT_ATTENTION_SECONDS,
}

DOMAIN = "nursery_soother"
ENTRY_VERSION = 7
EVENT_NOTIFICATION_ACTION = "mobile_app_notification_action"
NAME = "Nursery Soother"
NOTIFICATION_ACTION_PREFIX = "NURSERY_SOOTHER"
NOTIFICATION_TAG_PREFIX = "nursery-soother"
MAX_VOLUME_PERCENT = 100.0

ENTITY_DOMAINS: Final = {
    CONF_CRY_SENSOR: Platform.BINARY_SENSOR,
    CONF_CAMERA: Platform.CAMERA,
    CONF_MEDIA_PLAYER: Platform.MEDIA_PLAYER,
}

PLATFORMS: Final = (
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.NUMBER,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.SWITCH,
)

SERVICE_SIMULATE_CRY_EVENT = "simulate_cry_event"

ACTION_SET_LEVEL = "SET_LEVEL"
ACTION_SET_MANUAL = "SET_MANUAL"
