"""Constants for Nursery Soother."""

from typing import Final

from homeassistant.const import Platform

CONF_BASELINE_VOLUME = "baseline_volume"
CONF_BOOST_VOLUME = "boost_volume"
CONF_CAMERA = "camera"
CONF_COOLDOWN_SECONDS = "cooldown_seconds"
CONF_CRY_SENSOR = "cry_sensor"
CONF_DEBOUNCE_SECONDS = "debounce_seconds"
CONF_ENABLED = "enabled"
CONF_ESCALATION_SECONDS = "escalation_seconds"
CONF_MEDIA_PLAYER = "media_player"
CONF_NOTIFY_TARGETS = "notify_targets"
CONF_SETTLING_SECONDS = "settling_seconds"
CONF_WHITE_NOISE = "white_noise"
CONF_MAX_VOLUME = "max_volume"

DEFAULT_BASELINE_VOLUME = 20.0
DEFAULT_BOOST_VOLUME = 30.0
DEFAULT_COOLDOWN_SECONDS = 60
DEFAULT_DEBOUNCE_SECONDS = 15
DEFAULT_ENABLED = False
DEFAULT_ESCALATION_SECONDS = 120
DEFAULT_MAX_VOLUME = 40.0
DEFAULT_SETTLING_SECONDS = 120

DEFAULT_OPTIONS: Final = {
    CONF_BASELINE_VOLUME: DEFAULT_BASELINE_VOLUME,
    CONF_BOOST_VOLUME: DEFAULT_BOOST_VOLUME,
    CONF_MAX_VOLUME: DEFAULT_MAX_VOLUME,
    CONF_DEBOUNCE_SECONDS: DEFAULT_DEBOUNCE_SECONDS,
    CONF_COOLDOWN_SECONDS: DEFAULT_COOLDOWN_SECONDS,
    CONF_SETTLING_SECONDS: DEFAULT_SETTLING_SECONDS,
    CONF_ESCALATION_SECONDS: DEFAULT_ESCALATION_SECONDS,
    CONF_ENABLED: DEFAULT_ENABLED,
}

DOMAIN = "nursery_soother"
ENTRY_VERSION = 2
EVENT_NOTIFICATION_ACTION = "mobile_app_notification_action"
NAME = "Nursery Soother"
NOTIFICATION_ACTION_PREFIX = "NURSERY_SOOTHER"
NOTIFICATION_TAG_PREFIX = "nursery-soother"
MAX_VOLUME_PERCENT = 100.0

ENTITY_DOMAINS: Final = {
    CONF_CRY_SENSOR: Platform.BINARY_SENSOR,
    CONF_CAMERA: Platform.CAMERA,
    CONF_MEDIA_PLAYER: Platform.MEDIA_PLAYER,
}

PLATFORMS: Final = (
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.NUMBER,
    Platform.SENSOR,
    Platform.SWITCH,
)

SERVICE_ACKNOWLEDGE = "acknowledge"
SERVICE_BASELINE = "baseline"
SERVICE_BOOST = "boost"
SERVICE_STOP = "stop"
SERVICES: Final = (
    SERVICE_BOOST,
    SERVICE_BASELINE,
    SERVICE_ACKNOWLEDGE,
    SERVICE_STOP,
)

ACTION_ACKNOWLEDGE = "ACKNOWLEDGE"
ACTION_BASELINE = "BASELINE"
ACTION_BOOST = "BOOST"
ACTION_STOP = "STOP"
